apps/web-app/package.json
apps/web-app/src/components/Tabs/TabsPage.tsx
apps/web-app/src/components/Tweet/Tweet.tsx
apps/web-app/src/pages/User/components/UserHeader.tsx
pnpm-lock.yaml

feat(web-app): add skeletons for each component

---

apps/web-app/src/components/ToggleTheme/ToggleTheme.tsx

Add system button to make more easy to understand the ToggleTheme component

fix(web-app): fix theme button bug

---

apps/web-app/src/components/Header/Header.tsx
apps/web-app/src/pages/Login/components/LoginFooter.tsx
apps/web-app/src/pages/Register/components/RegisterFooter.tsx
apps/web-app/src/pages/User/hooks/useUserData.ts
apps/web-app/src/routing/Routing.tsx
apps/web-app/src/routing/guards/auth.guard.tsx
apps/web-app/src/routing/guards/public.guard.tsx
apps/web-app/src/routing/routes.model.ts
apps/web-app/src/services/auth.service.ts

restructure routes.model.ts file to have only one way to access to the routes of the app.

feat(web-app): add routes for back-end and fornt-end

---

Readme.md

feat(web-app): add routes for back-end and front-end

---

apps/web-app/package.json
apps/web-app/src/components/Header/Header.tsx
apps/web-app/src/components/HeaderMenu/HeaderMenu.tsx
apps/web-app/src/components/ToggleTheme/ToggleTheme.tsx
apps/web-app/src/components/ToggleTranslation/ToggleTranslation.tsx
apps/web-app/src/components/UserMenu/UserMenu.tsx
apps/web-app/src/components/index.ts
apps/web-app/src/hooks/index.ts
pnpm-lock.yaml

feat(web-app): update global header

---

apps/web-app/src/pages/User/components/UserHeader.tsx

feat(server) add external link to user profile #14

---

apps/web-app/public/locales/en/translation.json
apps/web-app/public/locales/es/translation.json
apps/web-app/src/components/DropDownMenu/DropDownMenu.tsx
apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/Header/Header.tsx
apps/web-app/src/components/ToggleTheme/ToggleTheme.tsx
apps/web-app/src/components/ToggleTranslation/ToggleTranslation.tsx
apps/web-app/src/components/UserMenu/UserMenu.tsx
apps/web-app/src/components/index.ts
apps/web-app/src/models/UI/inputs.model.tsx
apps/web-app/src/pages/Login/Login.tsx
apps/web-app/src/pages/Login/components/LoginFooter.tsx
apps/web-app/src/pages/Login/components/LoginHeader.tsx
apps/web-app/src/pages/Register/Register.tsx
apps/web-app/src/pages/Register/components/RegisterFooter.tsx
apps/web-app/src/pages/Register/components/RegisterHeader.tsx
apps/web-app/src/pages/User/components/UserHeader.tsx
apps/web-app/src/pages/User/components/UserMain.tsx

feat(web-app): update i18next translations #77

---

apps/web-app/src/components/DropDownListOfItems/DropDownListOfItems.tsx
apps/web-app/src/hooks/useToggleTheme.ts
apps/web-app/src/models/UI/theme.model.ts
pnpm-lock.yaml

feat(web-app): modify theme change icon #94

---

.husky/pre-commit
apps/web-app/cypress/e2e/userAuth.cy.ts
apps/web-app/cypress/e2e/userJourney.cy.ts
apps/web-app/cypress/support/commands.ts
apps/web-app/package.json
apps/web-app/src/utils/errorMessages.util.ts
apps/web-app/vite.config.ts
pnpm-lock.yaml

feat(web-app): add 2e2 test to git hooks #102

---

.github/workflows/pipeline.yaml
apps/web-app/src/context/Auth/authProvider.context.tsx
apps/web-app/src/layouts/MessageLayout.tsx
apps/web-app/src/pages/Settings/Settings.tsx
apps/web-app/src/pages/Settings/components/SettingsHeader/SettingsHeader.tsx
apps/web-app/src/pages/Settings/components/SettingsMain/SettingsMain.tsx
apps/web-app/src/pages/Settings/components/index.ts
apps/web-app/src/routing/Routing.tsx

feat(web-app): add settings page #84

---

apps/web-app/src/pages/User/components/UserHeader.tsx

ix(web-app): remove user page margin in user header #108

---

apps/web-app/public/locales/en/translation.json
apps/web-app/public/locales/es/translation.json
apps/web-app/src/components/DropDownListOfItems/DropDownListOfItems.tsx
apps/web-app/src/components/Header/Header.tsx
apps/web-app/src/context/Auth/authProvider.context.tsx
apps/web-app/src/hooks/index.ts
apps/web-app/src/hooks/useGlobalAuth.ts
apps/web-app/src/hooks/useLocalAuth.ts
apps/web-app/src/pages/Index/Index.tsx
apps/web-app/src/pages/Login/Login.tsx
apps/web-app/src/pages/Register/Register.tsx
apps/web-app/src/pages/User/User.tsx
apps/web-app/src/pages/index.ts
apps/web-app/src/routing/Routing.tsx
apps/web-app/src/routing/guards/auth.guard.tsx

feat(web-app): add user profile link in dropdown menu #116

---

apps/web-app/public/locales/en/translation.json
apps/web-app/public/locales/es/translation.json
apps/web-app/src/components/TabPanel/TabPanel.tsx
apps/web-app/src/hooks/useLocalAuth.ts

feat(web-app): add tab logic for global app use #118

---

.husky/commit-msg
commitlint.config.js
package.json
pnpm-lock.yaml

close #104
to solve some issues : 
```chmod u+x .husky/*``` in root dir

feat(app): add commitlint #104

---

apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/TabsPage.tsx
apps/web-app/src/config/axios/axios.interceptors.ts
apps/web-app/src/pages/Settings/Settings.tsx
apps/web-app/src/pages/Settings/components/PageStructure/SettingsMain.tsx
apps/web-app/src/pages/Settings/components/TabPanels/AccountTabPanel.tsx
apps/web-app/src/pages/Settings/models/UI/tabs.model.tsx
apps/web-app/src/pages/User/components/UserMain.tsx

feat(web-app): update tab system design for make it reusable #127

---

apps/web-app/src/pages/Home/Home.tsx
apps/web-app/src/pages/Home/config/index.ts
apps/web-app/src/pages/Home/config/metadata.config.ts
apps/web-app/src/pages/Index/Index.tsx
apps/web-app/src/pages/Login/Login.tsx
apps/web-app/src/pages/Login/config/index.ts
apps/web-app/src/pages/Login/config/metadata.config.ts
apps/web-app/src/pages/Register/Register.tsx
apps/web-app/src/pages/Register/config/index.ts
apps/web-app/src/pages/Register/config/metadata.config.ts
apps/web-app/src/pages/Settings/Settings.tsx
apps/web-app/src/pages/Settings/config/index.ts
apps/web-app/src/pages/Settings/config/metadata.config.ts
apps/web-app/src/pages/User/User.tsx
apps/web-app/src/pages/User/metadata.ts
apps/web-app/src/routing/Routing.tsx

refactor(web-app): refactor pages metadata #136

---

apps/web-app/src/components/TabsPage.tsx

feat(web-app): add responsive to setting page components #134

---

apps/web-app/src/utils/errorMessages.util.ts

feat(web-app): add server is down code to errorMessages const #139

---

apps/web-app/src/components/DropDownMenu/components/DropDownListOfItems/DropDownListOfItems.tsx
apps/web-app/src/components/Header.tsx
apps/web-app/src/components/TabsPage/TabsPage.tsx
apps/web-app/src/components/TabsPage/components/TabListElement.tsx
apps/web-app/src/components/TabsPage/components/index.ts
apps/web-app/src/components/index.ts
apps/web-app/src/models/UI/tabs.model.ts
apps/web-app/src/pages/Login/components/LoginFooter.tsx
apps/web-app/src/pages/Register/components/RegisterFooter.tsx
apps/web-app/src/pages/Settings/components/PageStructure/SettingsMain.tsx
apps/web-app/src/pages/Settings/components/TabPanels/HomeTabPanel.tsx
apps/web-app/src/pages/Settings/models/UI/tabs.model.tsx
apps/web-app/src/pages/Settings/routing/SettingsRouting.tsx
apps/web-app/src/pages/Settings/routing/index.ts
apps/web-app/src/pages/User/User.tsx
apps/web-app/src/pages/User/components/UserMain.tsx
apps/web-app/src/pages/User/hooks/useUserData.ts
apps/web-app/src/routing/Routing.tsx
apps/web-app/src/routing/guards/auth.guard.tsx
apps/web-app/src/routing/routes.model.ts
apps/web-app/src/services/auth.service.ts
apps/web-app/src/services/user.service.ts

feat(web-app): add routing for settings page #133

---

apps/web-app/package.json
apps/web-app/public/locales/en/translation.json
apps/web-app/public/locales/es/translation.json
apps/web-app/src/components/TabPanel.tsx
apps/web-app/src/components/TabsPage/TabsPage.tsx
apps/web-app/src/pages/Settings/Settings.tsx
apps/web-app/src/pages/Settings/components/PageStructure/SettingsMain.tsx
apps/web-app/src/pages/Settings/components/TabPanels/HomeTabPanel.tsx
apps/web-app/src/pages/Settings/models/UI/tabs.model.tsx
apps/web-app/src/pages/Settings/routing/SettingsRouting.tsx
apps/web-app/src/pages/User/components/UserMain.tsx

142 featweb app add default settings page

---

apps/web-app/src/config/axios/axios.interceptors.ts
apps/web-app/src/hooks/useUserMethods.ts

fix(web-app): fix user auth bug (#141)

---

apps/web-app/src/config/i18next/i18next.config.ts

dfix(web-app): translation cache #149

---

apps/web-app/cypress/e2e/userAuth.cy.ts
apps/web-app/cypress/support/e2e.ts

fix(web-app): fix e2e test (#147)

---

apps/web-app/src/context/Auth/auth.context.ts
apps/web-app/src/hooks/useLocalAuth.ts
apps/web-app/src/pages/Register/Register.tsx

feat(web-app): sign in when the user sign up #151

---

apps/web-app/src/components/DropDownMenu/DropDownMenu.tsx
apps/web-app/src/models/LOGIC/api.model.ts
apps/web-app/src/models/LOGIC/user.model.ts
apps/web-app/src/pages/User/User.tsx
apps/web-app/src/pages/User/components/UserHeader.tsx
apps/web-app/src/pages/User/hooks/useUserData.ts
apps/web-app/src/routing/routes.model.ts

feat(web-app): add user role information #163

---

apps/web-app/src/App.tsx
apps/web-app/src/config/axios/axios.interceptors.ts

feat(web-app): add server validation time out #161

---

apps/web-app/src/pages/User/components/UserHeader.tsx

feat(web-app): make profile description font size larger #169

---

apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/Form/components/DeterminateInput.tsx
apps/web-app/src/components/Form/components/Error.tsx
apps/web-app/src/components/Form/components/TextField.tsx
apps/web-app/src/components/Form/components/TextFieldAsync.tsx
apps/web-app/src/components/Form/hooks/index.ts
apps/web-app/src/components/Form/hooks/useAsyncValidations.ts
apps/web-app/src/components/Form/hooks/useDebounce.ts
apps/web-app/src/models/LOGIC/api.model.ts
apps/web-app/src/models/UI/form.model.tsx
apps/web-app/src/pages/Login/Login.tsx
apps/web-app/src/pages/Login/models/form.model.ts
apps/web-app/src/pages/Register/Register.tsx
apps/web-app/src/pages/Register/models/form.model.ts
apps/web-app/src/pages/Settings/components/TabPanels/AccountInformationTabPanel.tsx
apps/web-app/src/services/user.service.ts
apps/web-app/src/utils/checkServerStatus.util.ts

feat(server): fix database users seeding #158

---

apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/Form/components/DeterminateInput.tsx
apps/web-app/src/components/Form/components/TextFieldAsync.tsx
apps/web-app/src/components/Form/hooks/useAsyncValidations.ts
apps/web-app/src/models/UI/form.model.tsx
apps/web-app/src/pages/Register/models/form.model.ts
apps/web-app/src/pages/Settings/components/TabPanels/AccountInformationTabPanel.tsx

fix(web-app): fix some performance issues #158

---

apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/Form/adapters/defaultValues.adapter.ts
apps/web-app/src/components/Form/adapters/index.ts
apps/web-app/src/components/Form/components/DeterminateInput.tsx
apps/web-app/src/components/Form/components/TextFieldAsync.tsx
apps/web-app/src/components/Form/hooks/useAsyncValidations.ts
apps/web-app/src/components/Form/hooks/useDebounce.ts
apps/web-app/src/models/UI/form.model.tsx
apps/web-app/src/pages/Settings/components/TabPanels/AccountInformationTabPanel.tsx
apps/web-app/src/pages/Settings/models/UI/form.model.ts

feat(web-app): improve form logic #177

---

.gitignore
apps/server/src/controllers/auth/sign-in.ts
apps/server/src/controllers/user/index.ts
apps/server/src/providers/user/get.ts
apps/server/src/providers/user/udpate.ts
apps/web-app/public/locales/en/translation.json
apps/web-app/public/locales/es/translation.json
apps/web-app/src/pages/Settings/components/TabPanels/DeleteAccountTabPanel.tsx

@Jes015 add a message in the modal which opens when the user is going to delete the account. telling the user the account will be re-activated if he logs again

feat(server): implemented account recovery if user logs in again

---

apps/web-app/src/config/axios/axios.interceptors.ts

feat(web-app): show the server isn't available (#191)

---

apps/web-app/src/config/axios/axios.interceptors.ts

fix(web-app): lengthen abortcontroller timeout (#193)

---

apps/server/src/interfaces/user.interface.ts
apps/server/src/middlewares/validators/dietary-validator.ts
apps/server/src/middlewares/validators/email.ts
apps/server/src/middlewares/validators/index.ts
apps/server/src/models/user/user.ts
apps/server/src/routes/auth/index.ts
apps/server/src/routes/user/index.ts
apps/web-app/src/models/UI/form.model.tsx

added length validation in user update, while fixing the email validation.

feat(server): added validations in endpoints and database models

---

apps/web-app/.env.example
apps/web-app/src/config/axios/axios.interceptors.ts
apps/web-app/src/models/LOGIC/api.model.ts
apps/web-app/src/utils/errorMessages.util.ts

feat(web-app): add custom validaiton errors (#170)

---

apps/web-app/src/components/AppTabPanels/AccountInformationTabPanel.tsx
apps/web-app/src/components/DropZone.tsx
apps/web-app/src/utils/imageOptimizer.util.ts
apps/web-app/src/utils/index.ts

feat(web-app): image optimization (#215)

---

apps/server/src/controllers/token/index.ts
apps/server/src/utils/response-class.ts
apps/web-app/src/pages/User/User.tsx
apps/web-app/src/pages/User/hooks/useUserApiData.ts
apps/web-app/src/routing/guards/auth.guard.tsx
apps/web-app/src/utils/errorMessages.util.ts

fix(web-app): fix user not found bug (#218)

---

apps/web-app/public/locales/en/translation.json
apps/web-app/public/locales/es/translation.json
apps/web-app/src/models/UI/form.model.tsx
apps/web-app/src/pages/Settings/models/UI/form.model.ts

feat(web-app): add name input for user forms (#225)

---

apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/Form/adapters/defaultValues.adapter.ts
apps/web-app/src/components/Form/components/DeterminateInput.tsx
apps/web-app/src/components/Form/components/DropZone.tsx
apps/web-app/src/components/Form/components/TextArea.tsx
apps/web-app/src/components/Form/components/TextField.tsx
apps/web-app/src/components/Form/components/TextFieldAsync.tsx
apps/web-app/src/components/Form/models/form.model.ts
apps/web-app/src/components/Form/models/index.ts
apps/web-app/src/models/UI/form.model.tsx
apps/web-app/src/pages/Login/models/form.model.ts
apps/web-app/src/pages/Register/models/form.model.ts
apps/web-app/src/pages/Settings/models/UI/form.model.ts
apps/web-app/src/utils/checkServerStatus.util.ts
apps/web-app/src/utils/schemas.util.ts

refactor(web-app): refactor form models (#228)

---

apps/web-app/src/config/axios/axios.interceptors.ts
apps/web-app/src/services/user.service.ts

fix(web-app): add abort controller and image requests (#231)

---

apps/web-app/src/components/DropZone.tsx
apps/web-app/src/components/Image/Image.tsx
apps/web-app/src/pages/Settings/components/TabPanels/AccountInformationTabPanel.tsx
apps/web-app/src/utils/imageOptimizer.util.ts

feat(web-app): add blur image for user images (#239)

---

apps/web-app/src/pages/User/components/PageStructure/UserHeader.tsx

feat(web-app): add location to public profile and remove twitter link (#252)

---

apps/web-app/src/hooks/useUserMethods.ts

feat(web-app): fix profile not found after updating user username (#251)

---

apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/Form/adapters/form.adapter.ts
apps/web-app/src/components/Form/adapters/index.ts

fix(web-app): form does not allow to save user data (#257)

---

apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/Form/adapters/form.adapter.ts
apps/web-app/src/config/axios/axios.interceptors.ts
apps/web-app/src/hooks/useLocalAuth.ts
apps/web-app/src/pages/Settings/components/TabPanels/DietaryPreferencesTabPanel.tsx
apps/web-app/src/services/index.ts
apps/web-app/src/services/logger.service.ts
apps/web-app/src/utils/checkServerStatus.util.ts
apps/web-app/src/utils/index.ts
apps/web-app/src/utils/logger.util.ts

feat(web-app): delete console.logs (#250)

---

apps/web-app/src/components/DropDownMenu/DropDownMenu.tsx
apps/web-app/src/pages/Home/Home.tsx

refactor(web-app): remove home page content (#270)

---

apps/web-app/src/models/LOGIC/user.model.ts
apps/web-app/src/pages/User/components/PageStructure/UserHeader.tsx

feat(web-app): only render user role chip when role is admin #269

---

apps/web-app/src/components/DropDownMenu/DropDownMenu.tsx
apps/web-app/src/config/global.config.ts
apps/web-app/src/hooks/useLocalAuth.ts

fix(web-app): remove initial loading component to improve FCP (#290)

---

apps/web-app/package.json
apps/web-app/src/layouts/AuthLayout/AuthLayout.tsx
apps/web-app/src/layouts/index.ts
apps/web-app/src/pages/Login/Login.tsx
apps/web-app/src/pages/Register/Register.tsx
apps/web-app/src/routing/Routing.tsx
apps/web-app/src/routing/SuspenseRouter.tsx
apps/web-app/src/routing/index.ts
pnpm-lock.yaml

fix(web-app): avoid the blank page (#292)

---

apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/Form/components/DeterminateInput.tsx
apps/web-app/src/components/Form/components/DropZone.tsx
apps/web-app/src/components/PublicationBox.tsx
apps/web-app/src/components/StepViewer/components/StepViewerMain.tsx
apps/web-app/src/pages/Home/components/TabPanels/RecipesTabPanel.tsx
apps/web-app/src/pages/Home/models/form.model.ts
apps/web-app/src/pages/Login/Login.tsx
apps/web-app/src/pages/Register/Register.tsx
apps/web-app/src/pages/Settings/components/TabPanels/AccountInformationTabPanel.tsx
apps/web-app/src/pages/Settings/components/TabPanels/DietaryPreferencesTabPanel.tsx
apps/web-app/src/routing/SuspenseRouter.tsx

feat(web-app): add form footer inputs (#311)

---

apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/Form/components/CheckBox.tsx
apps/web-app/src/components/Form/components/DropZone/DropZone.tsx
apps/web-app/src/components/Form/components/TextArea.tsx
apps/web-app/src/components/Form/components/TextField.tsx
apps/web-app/src/components/Form/components/TextFieldAsync.tsx
apps/web-app/src/components/PublicationBox.tsx
apps/web-app/src/models/LOGIC/recipe.model.ts
apps/web-app/src/pages/Home/components/PageStructure/HomeHeader.tsx
apps/web-app/src/pages/Home/models/form.model.ts
apps/web-app/src/pages/Login/Login.tsx
apps/web-app/src/pages/Register/Register.tsx
apps/web-app/src/pages/Settings/components/TabPanels/AccountInformationTabPanel.tsx

feat(web-app): publication box fields (#318)

---

apps/web-app/src/components/Form/components/DropZone/DropZone.tsx
apps/web-app/src/components/Form/models/form.model.ts
apps/web-app/src/models/UI/form.model.tsx
apps/web-app/src/pages/Home/components/PageStructure/HomeHeader.tsx
apps/web-app/src/pages/Home/models/form.model.ts

feat(web-app): publication box form images (#321)

---

apps/web-app/src/components/Carousel/Carousel.tsx
apps/web-app/src/components/Carousel/hooks/useCarousel.ts
apps/web-app/src/components/Carousel/routing/carousel.routing.ts
apps/web-app/src/components/Carousel/routing/index.ts
apps/web-app/src/components/Image/Image.tsx

fix(web-app): carousel logic (#325)

---

apps/web-app/src/components/Carousel/Carousel.tsx
apps/web-app/src/components/Carousel/components/CircleCountButtons.tsx
apps/web-app/src/components/Carousel/components/index.ts
apps/web-app/src/components/Carousel/hooks/useCarousel.ts

feat(web-app): carousel buttons (#328)

---

apps/web-app/src/services/recipe.service.ts

fix(web-app): add correct headers to create recipe request (#332)

---

apps/web-app/package.json
apps/web-app/src/components/Form/components/DropZone/DropZone.tsx
apps/web-app/src/layouts/AuthLayout/components/Background/Background.tsx
apps/web-app/src/pages/Home/models/form.model.ts
pnpm-lock.yaml

fix(web-app): recipe types (#334)

---

apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/PublicationBox.tsx
apps/web-app/src/components/StepViewer/components/StepViewerMain.tsx
apps/web-app/src/pages/Home/components/PageStructure/HomeHeader.tsx
apps/web-app/src/pages/Home/models/form.model.ts
apps/web-app/src/pages/Login/Login.tsx
apps/web-app/src/pages/Register/Register.tsx
apps/web-app/src/pages/Settings/components/TabPanels/AccountInformationTabPanel.tsx

feat(web-app): add an expandable section to the Form component (#336)

---

apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/Form/components/DropZone/DropZone.tsx
apps/web-app/src/components/Form/components/DropZone/components/PopperDropZone/PopperDropZone.tsx

refactor(web-app): remove console.log (#343)

---

apps/web-app/src/components/Carousel/Carousel.tsx
apps/web-app/src/components/Image/models/image.model.ts
apps/web-app/src/components/Image/models/index.ts
apps/web-app/src/components/Recipe.tsx
apps/web-app/src/layouts/ContentLayout.tsx
apps/web-app/src/layouts/PostLayout/PostLayout.tsx
apps/web-app/src/models/LOGIC/recipe.model.ts
apps/web-app/src/pages/Home/components/Recipes.tsx
apps/web-app/src/pages/Recipe/RecipePage.tsx
apps/web-app/src/pages/User/components/PageStructure/UserMain.tsx
apps/web-app/src/routing/routes.model.ts
apps/web-app/src/services/recipe.service.ts

feat(web-app): add custom props to Recipe component (#347)

---

apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/Form/components/CheckBox.tsx
apps/web-app/src/components/Form/components/DeterminateInput.tsx
apps/web-app/src/components/Form/components/DropZone/DropZone.tsx
apps/web-app/src/components/Form/components/InputsArray.tsx
apps/web-app/src/components/Form/components/TextFieldAsync.tsx

feat(web-app): use react hook form provider for Form component (#349)

---

apps/web-app/src/components/DropZone.tsx
apps/web-app/src/components/Form/components/TextFieldAsync.tsx
apps/web-app/src/components/Image/models/image.model.ts
apps/web-app/src/components/Image/models/index.ts
apps/web-app/src/models/LOGIC/recipe.model.ts
apps/web-app/src/models/UI/image.model.ts
apps/web-app/src/models/UI/index.ts
apps/web-app/src/pages/Home/components/PageStructure/HomeHeader.tsx
apps/web-app/src/pages/Home/models/form.model.ts
apps/web-app/src/utils/imageMethods.util.ts
apps/web-app/src/utils/index.ts

feat(web-app): optimize the images added to the Publication box (#355)

---

apps/web-app/src/pages/Home/components/PageStructure/HomeHeader.tsx

fix(web-app): publicationBox is not sending images (#358)

---

apps/web-app/src/components/AddRecipe.tsx
apps/web-app/src/components/Form/components/DropZone/DropZone.tsx
apps/web-app/src/components/Form/components/DropZone/components/PopperDropZone/PopperDropZone.tsx
apps/web-app/src/components/Modal/Modal.tsx
apps/web-app/src/components/PublicationBox.tsx
apps/web-app/src/components/index.ts
apps/web-app/src/layouts/AppLayout/AppLayout.tsx
apps/web-app/src/layouts/PostLayout/PostLayout.tsx
apps/web-app/src/pages/Home/Home.tsx
apps/web-app/src/pages/Home/components/PageStructure/HomeMain.tsx
apps/web-app/src/pages/Home/components/index.ts

feat(web-app): move the publication box component (#362)

---

apps/web-app/src/components/Recipe.tsx

feat(web-app): update recipe components (#364)

---

apps/web-app/src/config/axios/axios.interceptors.ts
apps/web-app/src/utils/errorMessages.util.ts

feat(web-app): filter notifications from back (#368)

---

apps/web-app/src/components/AddRecipe.tsx
apps/web-app/src/models/LOGIC/recipe.model.ts

fix(web-app): remove the actual parser in addrecipe component (#375)

---

apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/Form/components/DeterminateInput.tsx
apps/web-app/src/components/Form/components/InputsArray.tsx
apps/web-app/src/components/Form/components/TextArea.tsx
apps/web-app/src/components/Form/components/TextField.tsx
apps/web-app/src/components/Form/components/TextFieldAsync.tsx
apps/web-app/src/components/StepViewer/StepViewer.tsx
apps/web-app/src/components/StepViewer/components/Step.tsx
apps/web-app/src/components/StepViewer/components/StepViewerHeader.tsx
apps/web-app/src/components/StepViewer/components/StepViewerMain.tsx
apps/web-app/src/components/StepViewer/hooks/index.ts
apps/web-app/src/components/StepViewer/hooks/useStep.ts
apps/web-app/src/components/StepViewer/hooks/useStepBox.ts
apps/web-app/src/components/StepViewer/hooks/useStepViewerMain.ts
apps/web-app/src/hooks/useRecipeMethods.ts
apps/web-app/src/layouts/ContentLayout.tsx
apps/web-app/src/models/LOGIC/recipe.model.ts
apps/web-app/src/pages/Cooking/Cooking.tsx
apps/web-app/src/routing/Routing.tsx
apps/web-app/src/routing/routes.model.ts
apps/web-app/src/services/recipe.service.ts

feat(web-app): work on cooking page (#377)

---

apps/web-app/src/components/Recipe.tsx
apps/web-app/src/layouts/MessageLayout.tsx
apps/web-app/src/layouts/PostLayout/PostLayout.tsx
apps/web-app/src/layouts/PostLayout/components/Structure/PostHeader.tsx
apps/web-app/src/models/LOGIC/api.model.ts

feat(web-app): update post layout headers (#381)

---

apps/web-app/src/components/AddRecipe.tsx
apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/GlobalLoading/LinearLoading.tsx
apps/web-app/src/config/axios/axios.interceptors.ts
apps/web-app/src/hooks/useRecipeMethods.ts

fix(web-app): addRecipe component is not notifying to the user any action (#383)

---

apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/Form/components/TextFieldAsync.tsx

fix(web-app): async inputs are not working (#387)

---

apps/landing/src/components/Sections/FunctionalitySection/FunctionalitySection.astro
apps/landing/src/components/Sections/FunctionalitySection/components/FunctionalitySubSection.astro
apps/landing/src/components/Sections/FunctionalitySection/components/Post.astro
apps/landing/src/components/Sections/FunctionalitySection/components/StepViewer.astro
apps/landing/src/components/Sections/FunctionalitySection/components/User.astro
apps/landing/src/components/Sections/FunctionalitySection/layouts/ComponentLayout.astro

feat(landing): add user component (#395)

---

apps/landing/src/components/PageStructure/Header.astro
apps/landing/src/components/PageStructure/Main.astro
apps/landing/src/components/Sections/FunctionalitySection/FunctionalitySection.astro
apps/landing/src/components/Sections/FunctionalitySection/components/FunctionalitySubSection.astro
apps/landing/src/layouts/Layout.astro

feat(landing): remove functionality section data (#404)

---

apps/web-app/src/components/Carousel/Carousel.tsx
apps/web-app/src/components/Carousel/hooks/useCarousel.ts
apps/web-app/src/layouts/ContentLayout.tsx
apps/web-app/src/models/LOGIC/recipe.model.ts
apps/web-app/src/models/UI/image.model.ts

fix(web-app): posts images are not displayed (#407)

---

apps/web-app/src/models/LOGIC/api.model.ts
apps/web-app/src/pages/User/User.tsx
apps/web-app/src/pages/User/components/PageStructure/UserMain.tsx
apps/web-app/src/pages/User/hooks/useUser.ts
apps/web-app/src/routing/routes.model.ts

feat(web-app): fetch user recipes in user page (#409)

---

apps/web-app/src/layouts/PostLayout/PostLayout.tsx
apps/web-app/src/pages/User/components/PageStructure/UserMain.tsx

refactor(web-app): remove tab navigation from user page (#411)

---

apps/web-app/src/components/Recipe.tsx
apps/web-app/src/layouts/PostLayout/PostLayout.tsx
apps/web-app/src/layouts/PostLayout/components/Skeleton/Skeleton.tsx

fix(web-app): remove skeletons to improve ux (#415)

---

apps/web-app/src/pages/User/components/PageStructure/UserMain.tsx
apps/web-app/src/pages/User/hooks/useUser.ts
apps/web-app/src/pages/User/hooks/useUserApiData.ts

fix(web-app): user page is not displaying the edit profile button (#419)

---

apps/web-app/src/components/Form/Form.tsx
apps/web-app/src/components/StepViewer/StepViewer.tsx
apps/web-app/src/components/StepViewer/components/StepViewerMain.tsx
apps/web-app/src/components/StepViewer/hooks/index.ts
apps/web-app/src/components/StepViewer/hooks/useStepViewerMain.ts
apps/web-app/src/components/StepViewer/hooks/useSyncStepsWithBackend.ts
apps/web-app/src/hooks/useRecipeMethods.ts
apps/web-app/src/models/LOGIC/recipe.model.ts
apps/web-app/src/services/recipe.service.ts

feat(web-app): integrate step viewer with back-end (#423)

---

apps/landing/src/components/Sections/FunctionalitySection/FunctionalitySection.astro
apps/web-app/src/components/AddRecipe.tsx
apps/web-app/src/pages/Home/models/form.model.ts

fix(web-app): fix form Home bugs (#428)

---

apps/web-app/src/components/StepViewer/StepViewer.tsx
apps/web-app/src/components/StepViewer/components/Step.tsx
apps/web-app/src/components/StepViewer/components/StepViewerMain.tsx
apps/web-app/src/components/StepViewer/hooks/useSyncStepsWithBackend.ts
apps/web-app/src/hooks/useRecipeMethods.ts
apps/web-app/src/services/recipe.service.ts

fix(web-app): fix step viewer put request bug (#430)

---

apps/web-app/src/components/StepViewer/StepViewer.tsx
apps/web-app/src/components/StepViewer/components/StepViewerHeader.tsx
apps/web-app/src/components/StepViewer/components/StepViewerMain.tsx
apps/web-app/src/components/StepViewer/hooks/useSyncStepsWithBackend.ts

fix(web-app): cooking page not found bug (#432)

---

apps/web-app/.eslintrc.cjs
apps/web-app/src/components/Form/components/DropZone/DropZone.tsx
apps/web-app/src/components/Form/components/DropZone/components/PopperDropZone/PopperDropZone.tsx
apps/web-app/src/components/Form/components/DropZone/components/PopperDropZone/hooks/index.ts
apps/web-app/src/components/Form/components/DropZone/components/PopperDropZone/hooks/usePopperDropZone.ts
apps/web-app/src/components/Form/components/DropZone/components/PopperDropZone/util/index.ts
apps/web-app/src/components/Form/components/DropZone/components/PopperDropZone/util/popperDropZone.util.ts
apps/web-app/src/pages/Home/models/form.model.ts
apps/web-app/tsconfig.json
pnpm-lock.yaml

feat(web-app): improve image input component (#436)

---

apps/web-app/src/components/Form/components/DropZone/components/PopperDropZone/PopperDropZone.tsx
apps/web-app/src/components/Form/components/DropZone/components/PopperDropZone/hooks/usePopperDropZone.ts
apps/web-app/src/pages/Home/models/form.model.ts

fix(web-app): recipe form images (#439)

---

apps/web-app/src/pages/Home/components/Recipes.tsx
apps/web-app/src/pages/User/components/PageStructure/UserMain.tsx

fix(web-app): remove cursor pointer from Recipe component (#462)
